- name: install utilities
  yum: name='{{item}}' state=present
  with_items: "{{ common_apps }}"
- name: Modify prompt
  template: src=prompt.sh.j2 dest=/etc/profile.d/prompt.sh
  when: shortname is defined
- name: Set hostname
  command: "/usr/bin/hostnamectl set-hostname {{server_hostname}}"
  when: (ansible_distribution_major_version == "7" and server_hostname is defined)
- name: Set timezone
  command: /usr/bin/timedatectl set-timezone {{ common_timezone }}
  when: ansible_distribution_major_version == "7" and common_timezone is defined
- name: configure postfix
  template: src=main.cf.j2 dest=/etc/postfix/main.cf owner="root" group="root" mode=0644
  when: mail_hostname is defined
  notify:
  - reload postfix
- name: Start firewalld
  service: name=firewalld state=started enabled=yes
  when: start_firewalld is defined and start_firewalld
- name: Stop firewalld
  service: name=firewalld state=stopped enabled=no
  when: start_firewalld is defined and not start_firewalld
- name: Set root mail
  lineinfile: "dest=/etc/aliases state=present regexp='^root:' line='root: {{rootmail}}' owner=root group=root mode=0644"
  when: rootmail is defined
  notify:
  - run newaliases
- name: configure journald
  template:
    dest: "/etc/systemd/journald.conf"
    src: "journald.conf.j2"
    owner: "root"
    group: "root"
    mode: 0644
  when: configure_journald

